"""add summary_type field

Revision ID: ba3907ca95da
Revises: 0ce16a2fccf3
Create Date: 2025-02-12 06:42:59.382532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba3907ca95da'
down_revision = '0ce16a2fccf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_type', sa.String(), nullable=False, server_default='daily'))

    # Update existing records to have 'daily' as their summary_type
    op.execute("UPDATE daily_summaries SET summary_type = 'daily' WHERE summary_type IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_summaries', schema=None) as batch_op:
        batch_op.drop_column('summary_type')

    # ### end Alembic commands ###
